### PR TITLE
Hide Review

### PR DESCRIPTION
**Pull request by Fluv42**
Only shows the Circular "Create Review" button when the user is authenticated. I am very surprised how easily this works.

### CODE REVIEW

**Review by CodeMonkey64 — DISMISSED** [review]
Looks good to me

**Review by jessicadpo — CHANGES_REQUESTED** [review]
- {% endif %} on line 169 of userpage.html should be removed
- Javascript for userpage still needs to be fixed (changes applied to homepage not applied to userpage, I think)

**Review by jessicadpo — APPROVED** [review]
Looks good!

**Comment by Fluv42** [comment]
Beeble Behemoth

**Comment by Fluv42** [comment]
I am happy to hear it looks good!

**Pull request merged**
